//! Fuzz Burn's autograd / backward pass.
//!
//! The fuzz input is an [`AutogradProgram`] AST generated by `arbitrary`.
//! The interpreter builds the compute graph, calls backward(), and asserts
//! that both leaf tensors received gradients.

#![no_main]

use fuzzburn::ir::{interpreter, program::AutogradProgram};
use libfuzzer_sys::fuzz_target;

fuzz_target!(|prog: AutogradProgram| {
    interpreter::run_autograd_program(&prog);
});
