//! Fuzz the Burn frontend tensor API (plain, no autograd).
//!
//! The fuzz input is a [`TensorProgram`] AST generated by `arbitrary`.
//! The interpreter walks the AST and dispatches to Burn; any panic/abort is a bug.
//!
//! # Environment variables: FUZZ_MODE, 
#![no_main]

use fuzzburn::ir::{interpreter, program::TensorProgram, FuzzConfig};
use libfuzzer_sys::fuzz_target;

fuzz_target!(|prog: TensorProgram| {
    let config = FuzzConfig::from_env();
    interpreter::run_tensor_program(&prog, config.mode);
});
