//! Fuzz Burn's autograd / backward pass.
//!
//! The fuzz input is an [`AutogradProgram`] AST generated by `arbitrary`.
//! The interpreter builds the compute graph, calls backward(), and asserts
//! that every leaf tensor received a gradient.
//!
//! # Environment variables
//!
//! | Variable          | Default | Description                                     |
//! |-------------------|---------|-------------------------------------------------|
//! | `FUZZ_NUM_INPUTS` | `2`     | Number of leaf tensors (1–8)                    |
//! | `FUZZ_MODE`       | `panic` | `continuous` = log+continue; else re-panic      |
//!
//! Example:
//! ```sh
//! FUZZ_NUM_INPUTS=4 FUZZ_MODE=continuous cargo +nightly fuzz run fuzz_autograd
//! ```

#![no_main]

use fuzzburn::ir::{interpreter, program::AutogradProgram, FuzzConfig};
use libfuzzer_sys::fuzz_target;

fuzz_target!(|prog: AutogradProgram| {
    let config = FuzzConfig::from_env();
    println!("=== Fuzz input (num_inputs={}) ===\n{}", config.num_inputs, prog.ssa(config.num_inputs));
    interpreter::run_autograd_program(&prog, &config);
});
