//! The instruction set for the fuzz IR.
//!
//! [`TensorRef`] is the "operand" type for binary ops in the autograd world.
//! `Leaf(u8)` holds a raw byte generated by `arbitrary`.  At runtime the
//! interpreter calls [`TensorRef::dispatch_leaf_idx`] which uses the
//! probabilistic stack algorithm to either **reuse** an existing leaf or
//! **introduce** a new one, up to `max_leaves`.  The number of live leaf
//! tensors is therefore *discovered* during execution, not declared upfront.

use std::fmt;
use arbitrary::Arbitrary;

// ─── operand reference ────────────────────────────────────────────────────────

/// Names a tensor in scope during autograd program execution.
///
/// The raw `u8` inside `Leaf` is the entropy source for the stack dispatch
/// algorithm; it does **not** directly index the leaf array.
#[derive(Arbitrary, Debug, Clone)]
pub enum TensorRef {
    /// A leaf tensor.  The byte drives [`TensorRef::dispatch_leaf_idx`].
    Leaf(u8),
    /// The current accumulated value (output of the previous op).
    Current,
}

impl TensorRef {
    /// Core leaf-stack dispatch — mirrors the `generate_terminal` algorithm
    /// from the `ast_generator` in pyreking/cse291y.
    ///
    /// Returns `None` for `Current` (caller should clone the accumulator).
    /// Returns `Some((leaf_idx, new_stack_size))` for `Leaf`:
    /// - If `new_stack_size > num_used` a **new** leaf must be instantiated at
    ///   `leaf_idx` (which equals `num_used`) and pushed onto the stack.
    /// - Otherwise an **existing** leaf is reused.
    ///
    /// Probability of reuse grows with stack fullness:
    /// `P(reuse) = num_used / (num_used + num_available)`
    pub fn dispatch_leaf_idx(&self, num_used: usize, max_leaves: usize) -> Option<(usize, usize)> {
        match self {
            TensorRef::Current => None,
            TensorRef::Leaf(raw) => {
                let raw = *raw as usize;
                let num_available = max_leaves.saturating_sub(num_used);

                Some(if num_used == 0 {
                    // Stack is empty: always introduce x_0.
                    (0, 1)
                } else if num_available == 0 {
                    // Stack full: must reuse.
                    (raw % num_used, num_used)
                } else {
                    // Reuse probability = num_used / (num_used + num_available).
                    // Encoded as: raw < threshold  →  reuse.
                    let threshold = (num_used * 256) / (num_used + num_available);
                    if raw < threshold {
                        (raw % num_used, num_used)
                    } else {
                        // Introduce new leaf at the next available slot.
                        (num_used, num_used + 1)
                    }
                })
            }
        }
    }

    /// Resolve the display name given a concrete leaf index.
    pub fn name(&self, num_used: usize, max_leaves: usize) -> String {
        match self.dispatch_leaf_idx(num_used, max_leaves) {
            None => "t".to_string(),
            Some((idx, _)) => format!("x_{idx}"),
        }
    }
}

impl fmt::Display for TensorRef {
    /// Used in SSA Display where num_inputs is not statically known;
    /// shows the raw index so the reader can apply `% num_inputs` mentally.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TensorRef::Leaf(i) => write!(f, "x_{}", i),
            TensorRef::Current => write!(f, "t"),
        }
    }
}

// ─── plain tensor ops ─────────────────────────────────────────────────────────

/// Every tensor op we can fuzz against a non-differentiable backend.
/// Binary ops always use `self ⊕ self`; there is only one tensor in scope.
#[derive(Arbitrary, Debug, Clone)]
pub enum TensorOp {
    // --- binary (self ⊕ self) ---
    Add,
    Sub,
    Mul,
    // --- unary elementwise ---
    Neg,
    Abs,
    Exp,
    Log,
    Sqrt,
    // --- activations ---
    Relu,
    Sigmoid,
    Tanh,
    // --- reductions (output becomes [1, 1] for all following ops) ---
    SumAll,
    MeanAll,
    // --- layout ---
    Transpose,
    // --- guard against runaway values ---
    Clamp,
}

impl TensorOp {
    /// Render one SSA assignment line, e.g. `"t2 = exp(t1)"`.
    pub fn ssa_line(&self, out: &str, inp: &str) -> String {
        match self {
            TensorOp::Add      => format!("{out} = {inp} + {inp}"),
            TensorOp::Sub      => format!("{out} = {inp} - {inp}"),
            TensorOp::Mul      => format!("{out} = {inp} * {inp}"),
            TensorOp::Neg      => format!("{out} = -{inp}"),
            TensorOp::Abs      => format!("{out} = abs({inp})"),
            TensorOp::Exp      => format!("{out} = exp({inp})"),
            TensorOp::Log      => format!("{out} = log({inp})"),
            TensorOp::Sqrt     => format!("{out} = sqrt({inp})"),
            TensorOp::Relu     => format!("{out} = relu({inp})"),
            TensorOp::Sigmoid  => format!("{out} = sigmoid({inp})"),
            TensorOp::Tanh     => format!("{out} = tanh({inp})"),
            TensorOp::SumAll   => format!("{out} = sum({inp})  # → [1,1]"),
            TensorOp::MeanAll  => format!("{out} = mean({inp})  # → [1,1]"),
            TensorOp::Transpose => format!("{out} = {inp}.T"),
            TensorOp::Clamp    => format!("{out} = clamp({inp}, -1e6, 1e6)"),
        }
    }
}

// ─── differentiable ops ───────────────────────────────────────────────────────

/// The differentiable subset of ops.  Binary ops carry a [`TensorRef`] so the
/// interpreter can build a real DAG instead of a straight chain.
#[derive(Arbitrary, Debug, Clone)]
pub enum DiffOp {
    // --- binary: t ⊕ ref ---
    Add(TensorRef),
    Sub(TensorRef),
    Mul(TensorRef),
    // --- unary ---
    Neg,
    Exp,
    Log,
    Sqrt,
    // --- activations ---
    Sigmoid,
    Tanh,
    // --- reduction ---
    SumAll,
    // --- guard ---
    Clamp,
}

impl DiffOp {
    /// Render one SSA assignment line, e.g. `"t2 = t1 + b"`.
    /// `inp` is the current accumulator name (usually `"tN"`).
    pub fn ssa_line(&self, out: &str, inp: &str) -> String {
        match self {
            DiffOp::Add(r)  => format!("{out} = {inp} + {r}"),
            DiffOp::Sub(r)  => format!("{out} = {inp} - {r}"),
            DiffOp::Mul(r)  => format!("{out} = {inp} * {r}"),
            DiffOp::Neg     => format!("{out} = -{inp}"),
            DiffOp::Exp     => format!("{out} = exp({inp})"),
            DiffOp::Log     => format!("{out} = log({inp})"),
            DiffOp::Sqrt    => format!("{out} = sqrt({inp})"),
            DiffOp::Sigmoid => format!("{out} = sigmoid({inp})"),
            DiffOp::Tanh    => format!("{out} = tanh({inp})"),
            DiffOp::SumAll  => format!("{out} = sum({inp})  # → [1,1]"),
            DiffOp::Clamp   => format!("{out} = clamp({inp}, -1e6, 1e6)"),
        }
    }
}
