//! The instruction set for the fuzz IR.
//!
//! [`TensorRef`] is the "operand" type for binary ops in the autograd world.
//! `Leaf(u8)` holds an arbitrary-generated index that is reduced `% num_inputs`
//! at runtime, so it automatically scales when the number of leaves changes.

use std::fmt;
use arbitrary::Arbitrary;

// ─── operand reference ────────────────────────────────────────────────────────

/// Names a tensor in scope during autograd program execution.
///
/// `Leaf(i)` refers to leaf `i % num_inputs` – the raw byte is generated by
/// `arbitrary` and the interpreter folds it to a valid index at runtime.
#[derive(Arbitrary, Debug, Clone)]
pub enum TensorRef {
    /// A named input leaf (index = byte % num_inputs at runtime).
    Leaf(u8),
    /// The current accumulated value (output of the previous op).
    Current,
}

impl TensorRef {
    /// Resolve the display name when `num_inputs` is known.
    pub fn name(&self, num_inputs: usize) -> String {
        match self {
            TensorRef::Leaf(i) => format!("x_{}", (*i as usize) % num_inputs.max(1)),
            TensorRef::Current => "t".to_string(),
        }
    }
}

impl fmt::Display for TensorRef {
    /// Used in SSA Display where num_inputs is not statically known;
    /// shows the raw index so the reader can apply `% num_inputs` mentally.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TensorRef::Leaf(i) => write!(f, "x_{}", i),
            TensorRef::Current => write!(f, "t"),
        }
    }
}

// ─── plain tensor ops ─────────────────────────────────────────────────────────

/// Every tensor op we can fuzz against a non-differentiable backend.
/// Binary ops always use `self ⊕ self`; there is only one tensor in scope.
#[derive(Arbitrary, Debug, Clone)]
pub enum TensorOp {
    // --- binary (self ⊕ self) ---
    Add,
    Sub,
    Mul,
    // --- unary elementwise ---
    Neg,
    Abs,
    Exp,
    Log,
    Sqrt,
    // --- activations ---
    Relu,
    Sigmoid,
    Tanh,
    // --- reductions (output becomes [1, 1] for all following ops) ---
    SumAll,
    MeanAll,
    // --- layout ---
    Transpose,
    // --- guard against runaway values ---
    Clamp,
}

impl TensorOp {
    /// Render one SSA assignment line, e.g. `"t2 = exp(t1)"`.
    pub fn ssa_line(&self, out: &str, inp: &str) -> String {
        match self {
            TensorOp::Add      => format!("{out} = {inp} + {inp}"),
            TensorOp::Sub      => format!("{out} = {inp} - {inp}"),
            TensorOp::Mul      => format!("{out} = {inp} * {inp}"),
            TensorOp::Neg      => format!("{out} = -{inp}"),
            TensorOp::Abs      => format!("{out} = abs({inp})"),
            TensorOp::Exp      => format!("{out} = exp({inp})"),
            TensorOp::Log      => format!("{out} = log({inp})"),
            TensorOp::Sqrt     => format!("{out} = sqrt({inp})"),
            TensorOp::Relu     => format!("{out} = relu({inp})"),
            TensorOp::Sigmoid  => format!("{out} = sigmoid({inp})"),
            TensorOp::Tanh     => format!("{out} = tanh({inp})"),
            TensorOp::SumAll   => format!("{out} = sum({inp})  # → [1,1]"),
            TensorOp::MeanAll  => format!("{out} = mean({inp})  # → [1,1]"),
            TensorOp::Transpose => format!("{out} = {inp}.T"),
            TensorOp::Clamp    => format!("{out} = clamp({inp}, -1e6, 1e6)"),
        }
    }
}

// ─── differentiable ops ───────────────────────────────────────────────────────

/// The differentiable subset of ops.  Binary ops carry a [`TensorRef`] so the
/// interpreter can build a real DAG instead of a straight chain.
#[derive(Arbitrary, Debug, Clone)]
pub enum DiffOp {
    // --- binary: t ⊕ ref ---
    Add(TensorRef),
    Sub(TensorRef),
    Mul(TensorRef),
    // --- unary ---
    Neg,
    Exp,
    Log,
    Sqrt,
    // --- activations ---
    Sigmoid,
    Tanh,
    // --- reduction ---
    SumAll,
    // --- guard ---
    Clamp,
}

impl DiffOp {
    /// Render one SSA assignment line, e.g. `"t2 = t1 + b"`.
    /// `inp` is the current accumulator name (usually `"tN"`).
    pub fn ssa_line(&self, out: &str, inp: &str) -> String {
        match self {
            DiffOp::Add(r)  => format!("{out} = {inp} + {r}"),
            DiffOp::Sub(r)  => format!("{out} = {inp} - {r}"),
            DiffOp::Mul(r)  => format!("{out} = {inp} * {r}"),
            DiffOp::Neg     => format!("{out} = -{inp}"),
            DiffOp::Exp     => format!("{out} = exp({inp})"),
            DiffOp::Log     => format!("{out} = log({inp})"),
            DiffOp::Sqrt    => format!("{out} = sqrt({inp})"),
            DiffOp::Sigmoid => format!("{out} = sigmoid({inp})"),
            DiffOp::Tanh    => format!("{out} = tanh({inp})"),
            DiffOp::SumAll  => format!("{out} = sum({inp})  # → [1,1]"),
            DiffOp::Clamp   => format!("{out} = clamp({inp}, -1e6, 1e6)"),
        }
    }
}
